pose_initialize_node:
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    utm_topic: "gps/odom"
    gnss_pose_topic: "gps/position"
    map_origin: [492818.601536, 5527517.3772, 0] #[x, y, heading]  

    use_initializer: true
    timer_duration: 0.1
    examine_duration: 60
